### PR TITLE
clear code all SVG icons. redesign ubuntu-mono & hicolor. Add 16-96px…

### PR DESCRIPTION
**Pull request by varlesh**
… hicolor icon sizes & 16-24px ubuntu-mono icons

### CODE REVIEW

**Comment by varlesh** [comment]
#85

**Comment by varlesh** [comment]
Also setup.py updated too

**Comment by Kilian** [comment]
The cleaned up SVG's are great, thanks! I don't think the various sizes are required though.

**Comment by varlesh** [comment]
> The cleaned up SVG's are great, thanks! I don't think the various sizes are required though.

Little icons used on some launchers (Wicker Menu on XFCE for example or on KMenu on KDE)

**Comment by varlesh** [comment]
Also monochrome ubuntu-mono icons have different icon size too, because on Unity used 22px as standard, but on Gnome 16px by default... it's needed for pixel align

**Comment by ntc2** [comment]
Thanks!

**Pull request merged**
