### PR TITLE
Add redshift support

### LINKED ISSUE #113: Add a Redshift backend to fluxgui (or abandon the project!)
There's been no progress on #27 for two years, and now `xflux` doesn't work on either of the computers I (the `fluxgui` maintainer) use regularly. On the other hand, `redshift-gtk` works great on both those computers. So, I'm thinking that either `fluxgui` should be abandoned until `xflux` is fixed, or we should add a [Redshift](http://jonls.dk/redshift/) backend.

Is there some benefit to continuing this project when there is a viable alternative in `redshift-gtk`, and seemingly no future for `xflux`?

Thoughts? Pull requests?

### PR DESCRIPTION
**Pull request by LaBatata101**
closes #113 
needs more testing and some code refactoring

### CODE REVIEW

**Comment by ntc2** [comment]
Thanks! I haven't had a chance to look into this yet, but is it ready for me to test?

**Comment by LaBatata101** [comment]
Yes, is read for you to test it.

Sent from Samsung Mobile

-------- Original message --------

**Comment by ntc2** [comment]
@LaBatata101 sorry, I forgot about this and never reviewed it. If you've tested this and think it's ready to be merged, please go ahead and merge it yourself; I just invited you to have write access to this repo. If you could also update the docs and changelog to mention the new Redshift support you added, that would be good too. Thanks!

**Comment by LaBatata101** [comment]
No problem. When I get more free time I will test more and then merge it.

**Comment by peepopoggers** [comment]
:sob: when

**Pull request merged**
